version: '3.8'

services:
  fastapi-app:
    build: .
    container_name: fastapi-app
    command: "uvicorn main:app --host 0.0.0.0 --port 8000 --reload"
    ports:
      - "8000:8000"
    volumes:
      - .:/app  # Mount the current directory to /app in the container
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    depends_on:
      - db

  db:
    image: postgres:latest
    container_name: db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.dev.conf:/etc/nginx/nginx.conf
      - ./static:/usr/share/nginx/html
    depends_on:
      - fastapi-app

  react-app:
    build:
      context: ./react/inflationfast
      dockerfile: dockerfile.dev
    container_name: react-app
    ports:
      - "3000:3000"
    depends_on:
      - nginx

volumes:
  postgres_data:
