version: '3.8'

services:
  fastapi-app:
    command: "uvicorn main:app --host 0.0.0.0 --port 8000"
    restart: always

  nginx:
    ports:
      - "443:443"
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
      - ./nginx.conf:/etc/nginx/nginx.conf
    restart: always

  db:
    restart: always

  react-app:
    build:
      context: ./react/inflationfast
      dockerfile: dockerfile
    restart: always
    container_name: react-app
